export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST";
export const GET_SINGLE_PRODUCT_BY_ID = "GET_SINGLE_PRODUCT_BY_ID";
export const GET_CURRENCIES_LIST = "GET_CURRENCIES_LIST";
export const ADD_PRODUCT = "ADD_PRODUCT";
